SELECT [ProductCategoryKey]
      --,[ProductCategoryAlternateKey]
      ,[EnglishProductCategoryName]
      --,[SpanishProductCategoryName]
      --,[FrenchProductCategoryName]
  FROM [AdventureWorksDW2022].[dbo].[DimProductCategory]
