SELECT [ProductSubcategoryKey]
      --,[ProductSubcategoryAlternateKey]
      ,[EnglishProductSubcategoryName]
      --,[SpanishProductSubcategoryName]
      --,[FrenchProductSubcategoryName]
      ,[ProductCategoryKey]
  FROM [AdventureWorksDW2022].[dbo].[DimProductSubcategory]
